# **Tugas 2 (Pipelines)**

## Import Database

Data yang digunakan adalah data Iris dengan nama kolom sepallength, sepal_w, petallength, petalwidth.
Database yang digunakan antara lain :

1. PostgreSQL

2. Elephant

3. MySQL

4. SQL Server

## Get Data From DB



1.   PostgreSQL

     Kemudian diquery untuk mendapatkan kolom yang ada didatabase PostgreSQL. kolom yang diambil merupakan kolom sepallength dari tabel iris. library yang digunakan untuk mengakses database ini yaitu import psycopg2.

2. Elephant

   Untuk mengakses database Elephant yang ada di postgreSQL, menggunakan library import psycopg2. kemudian didalam library tersebut ada parameter yang harus dimasukkan. data yang diambil dari kolom sepal_w dari tabel iris.

3. MySQL

   Untuk mengakses database MySQL menggunakan library mysql-connector. agar bisa diakses publik, dapat menggunakan ngrok. didalam parameter mysql.connector disetting host dan port sesuai ngrok yang disediakan. data yang diambil dari kolom petallength dari tabel iris.

4. CSV

   Karena SQL Server tidak dapat diakses oleh orchest, maka diganti dengan data CSV dengan kolom petalwidth dan class. untuk mengakses data CSV tersebut menggunakan library pandas.

## Merge Data

Untuk menggabungkan dataframe, disini menggunakan join dengan bantuan library pandas.

## Load Model

Model yang digunakan adalah KNN, Naive Bayes Gaussian dan Random Forest.

## Hasil Akurasi

KNeighborsClassifier    = 1.0

random-forest-accuracy  = 0.9666666666666667

GaussianNB              = 0.9666666666666667

## Implementasi Code

In [ ]:
# import pyodbc
# import pandas as pd
# import psycopg2
# import mysql.connector
# import numpy as np

In [ ]:
## PostgreSQL Local (SepalLength)


# connpg = psycopg2.connect(
#     database="prosain200411100093",
#     user="postgres",
#     password="123",
#     host="localhost",
#     port="5432"
# )

# curpg = connpg.cursor()

# curpg.execute("SELECT sepallength FROM iris")

# sl = curpg.fetchall()

# sl=pd.DataFrame(sl,columns=['SepalLength'])

In [ ]:
## PostgreSQL Elephant (SepalWidth)


# connelp = psycopg2.connect(
#     database="tvmwqmdq",
#     user="tvmwqmdq",
#     password="NstogprqB_bGtXnU7hkfK9FZlgDKa0Yd",
#     host="isilo.db.elephantsql.com",
#     port="5432"
# )

# curelp = connelp.cursor()

# curelp.execute("SELECT sepal_w FROM data_iris")

# sw = curelp.fetchall()

# sw=pd.DataFrame(sw,columns=['SepalWidth'])

In [ ]:
## MYSQL Local (PetalLength)


# connmy = mysql.connector.connect(
#     host="localhost",
#     user="root",
#     password="",
#     database="prosain200411100093"
# )

# mycursor = connmy.cursor()

# mycursor.execute("SELECT Petallength FROM iris")

# myresult = mycursor.fetchall()

# # plot the data to data frame
# pl = pd.DataFrame(myresult, columns=['PetalLength',])

In [ ]:
## SQL Server (Petal Width, Class)


# server = 'LAPTOP-IFVCN1N7' 
# database = 'prosain200411100093' 
# username = 'sa' 
# password = 'admin'  

# cnxn = pyodbc.connect('DRIVER={ODBC Driver 17 for SQL Server};SERVER='+server+';DATABASE='+database+';UID='+username+';PWD='+ password)
# cursor = cnxn.cursor()

# querypw = "SELECT petalwidth FROM [prosain200411100093].[dbo].[data iris]"
# querycl = "SELECT class FROM [prosain200411100093].[dbo].[data iris]"

# cursor.execute(querypw)
# pw = cursor.fetchall()
# cursor.execute(querycl)
# cl = cursor.fetchall()

# np_pw = np.array(pw)
# np_cl = np.array(cl)

# np_pwcls = np.concatenate((np_pw, cl), axis=1)

# pwcls = pd.DataFrame(np_pwcls, columns=['PetalWidth', 'Class'])
# pwcls.head()

In [ ]:
# df = pd.concat([sl, sw, pl, pwcls], axis=1)

# print(df.head())

In [ ]:
# convert to csv


# pl.to_csv('pl_iris.csv', index=False)
# sl.to_csv('sl_iris.csv', index=False)
# sw.to_csv('sw_iris.csv', index=False)
# pwcls.to_csv('pwcls_iris.csv', index=False)